#
# Copyright (C) 2022-2023 Lin Song <linsongui@gmail.com>

name: test_set_2

on: workflow_call

jobs:
  test_set_2:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'hwdsl2'
    strategy:
      matrix:
        os_version: ["debian:12", "debian:11", "debian:10"]
      fail-fast: false
    container:
      image: ${{ matrix.os_version }}
      options: --cap-add=NET_ADMIN --device=/dev/net/tun
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Test
        run: |
          set -ex

          mkdir -p /opt/src
          cd /opt/src
          ls -ld "$GITHUB_WORKSPACE/openvpn-install.sh"

          export DEBIAN_FRONTEND=noninteractive
          apt-get -yqq update
          apt-get -yqq dist-upgrade
          apt-get -yqq install wget kmod procps net-tools

          cp -f "$GITHUB_WORKSPACE"/openvpn-install.sh ./openvpn.sh

          bash openvpn.sh --auto

          ls -ld ~/client.ovpn
